### ISSUE TITLE
ERROR in AngularSplitModule is not an NgModule

### ISSUE THREAD

**Issue by alokparikh16** [bertrandg/angular-split#70]
I am trying to use this module in my angular 4.3.5 application, angular cli: 1.0.6 but getting the below error:
ERROR in AngularSplitModule is not an NgModule

I edited angularSplit.module.d.ts file as below at my end and it worked as expected:

import { ModuleWithProviders } from '@angular/core';
export declare function delayedInit(): ModuleWithProviders;
export declare class AngularSplitModule {
    static forRoot: ModuleWithProviders;
}

What can be the resolution for the same?
Do I need to do anything at my end while importing the module?

**Comment by jspainhower** [comment]
Yup. Ran into exact same issue here.

**Comment by bertrandg** [comment]
@alokparikh16 @jspainhower @sergiusSidorov please provide me:

__Current failing config:__
* `@angular/*` version
* `cli` version
* `angular-split` version

__Previous working config (il there is one):__
* `@angular/*` version
* `cli` version
* `angular-split` version

@alokparikh16 No normally you just have to install it and import the module inside your module.. Maybe the cli version is a bit [old](https://github.com/angular/angular-cli/releases/tag/v1.0.6), lots of things were updated since then...

With versions, I will try to reproduce it and see how it could be solved.

**Comment by alokparikh16** [comment]
@bertrandg Please find the below configs which is causing issue:

- @angular/* version: 4.3.5
- cli version: 1.0.6
- angular-split version: 0.2.7
- typescript version: 2.4

However, I kept all the above configs same and tried installing angular-split v0.2.2 and it worked but it is not working with the latest 0.2.7 version.

I am not sure but I think there might be an issue with how the package is built.
Hope this might help: [https://www.usefuldev.com/blog/post/using-ngc-to-build-an-angular-2-library-project](url)

**Comment by bertrandg** [comment]
thanks for the details.

That's weird because (I know it's a mess, i screwed up on this!):
* `0.2.7` is a copy of `0.2.3` to don't break SemVer (https://github.com/bertrandg/angular-split/issues/66).
* `0.2.2` to `0.2.3`: I only moved `dependencies` to `peerDependencies` in `package.json` to be compatible with angular `5.0.0` https://github.com/bertrandg/angular-split/commit/c19b17d4e200d9ca00d5f278d75543870298f97a and https://github.com/bertrandg/angular-split/commit/14189c5e979a69c4c3e05ee7a6b7b24ac01d9e26.
* `0.2.5` & `0.2.6`: I didn't add any features or bug fixs, I just updated tooling & files organisation, sadly angular `5.0.0` was needed after these changes, this is why I published `0.2.7` to not break rules like `"angular-split": "^0.2.2"`..

To summerize versions compatibility:
* angular-split `1.0.0-beta-x` -> angular `5.x` min
* angular-split `0.2.7` -> angular `4.x` min
* angular-split `0.2.6` -> angular `5.x` min
* angular-split `0.2.5` -> angular `5.x` min
* angular-split `0.2.3` -> angular `4.x` min
* angular-split `0.2.2` -> angular `4.x` min

So `0.2.7` should works if `0.2.2` works..
Anyway, it doesn't add anything so lock it to `0.2.2` for now..

**Comment by bertrandg** [comment]
Try to uninstall before reinstall it:
`npm uninstall angular-split`
`npm install angular-split@0.2.7`

**Comment by alokparikh16** [comment]
Well, I tried reinstalling v0.2.7 again after uninstalling 0.2.2 but still the issue persist.
I switched back to 0.2.2 and it worked fine.

I guess I will stick with 0.2.2 as of now till we move to Angular 5 and then maybe upgrade the angular-split version.
Thanks.

**Comment by bkinsey808** [comment]
I love this project, but I can't get your npm distribution to work in the angular universal repo with a ssr build. Have you tried? I'm getting an error similar to the one the OP posted.

https://github.com/angular/universal-starter

To get it working, I had to put your source code directly into my project. Are you using an angular library seed?

**Comment by bertrandg** [comment]
Good question, never tried with ssr..
Are using `0.2.2` with angular `4.x` or `1.0.0-beta.x` with angular `5.x`?

**Comment by Skrutten** [comment]
Hi, 
I get the same error. 
Runnint angular 5.x

**Comment by szeplovitch95** [comment]
Hi, 
I am getting the exact same error.
I am using Angular 5.0.0 and it doesn't work with either 0.2.2 or 0.2.7. 
Running "ng serve" works fine but when I try to build it for prod, it fails.

**Comment by n614cd** [comment]
Same error with 0.2.7
Changed to 0.2.6 and issue went away
Cli: 1.5.4
Angular: 5.0.0
Split: 0.2.6
Typescript 2.5.3

I was on 0.2.2 with Angular 4 something; upgraded to Angular 5 and had compile issues. Then started chasing version.

Tim

**Comment by bertrandg** [comment]
Ok thanks for the details @n614cd 

Anyway, for everybody __using angular `5.x`__, please __use latest `angular-split@1.x`__ (currently `1.0.0-beta-9`).
Even if it's tagged beta (RC coming this week), it's more robust than `0.2.x`.
You can have a look on preview [doc](https://bertrandg.github.io/angular-split/beta/#/documentation) & [demo](https://bertrandg.github.io/angular-split/beta/#/examples/geek-demo).

And for people __using angular `4.x`__, __use `angular-split@0.2.6` or `angular-split@0.2.7`__, that's same library version with different tooling..

**Comment by n614cd** [comment]
@bertrandg 
None of the beta versions show in the NPM list.
I am checking available versions via "npm show angular-split@* version"
Just to verify, I tried naming the beta version directly, and NPM cannot find it. I considered doing a git pull, and going off source code but decided against it at this time.

**Comment by bertrandg** [comment]
Weird...
Try `npm view angular-split versions`:

![image](https://user-images.githubusercontent.com/7031941/33268582-0b361c44-d37e-11e7-9cfc-8e27a5bbe547.png)

**Comment by bertrandg** [comment]
@n614cd My mistake sorry,
I typed `1.0.0-beta-9` instead of `1.0.0-beta.9`!

**Comment by codech3ry** [comment]
I'm facing the same issue here and when I use 1.0.0-beta.9 and do prod build, it fails with Maximum call stack size exceeded....

**Comment by n614cd** [comment]
No error for me on Beta 9.

**Comment by nachocoig** [comment]
I don't understand. 

I've Angular 4.X, and angular-split 0.2.7

Yesterday, all worked correctly, but now, when i throw ng serve command, I receive the same message:

**AngularSplitModule is not an NgModule**

**Comment by nachocoig** [comment]
Now, i update Angular (I 've Angular 5.0.3), and i try to install angular-split 0.2.2, 0.2.6, 0.2.7 and 1.0.0-beta.9.

But now, the error is this:

Metadata version mismatch for module [...]/src/app/app.module.ts, found version 3, expected 4
    at StaticSymbolResolver.getModuleMetadata
